#!/usr/bin/perl -w
# Copyright © 2010 Kevin Spencer <kevin@kevinspencer.org>
#
# Permission to use, copy, modify, distribute, and sell this software and its
# documentation for any purpose is hereby granted without fee, provided that
# the above copyright notice appear in all copies and that both that
# copyright notice and this permission notice appear in supporting
# documentation.  No representations are made about the suitability of this
# software for any purpose.  It is provided "as is" without express or 
# implied warranty.
#
################################################################################

use File::Copy;
use File::Path;
use File::Spec;
use File::stat;
use Time::localtime;
use strict;

our $VERSION = '0.01';

my $user    = getpwuid($<);
my $BASEDIR = "/Users/$user/Pictures";

processDirectory($BASEDIR);

sub processDirectory {
    my $dir = shift;

    print "Processing $dir\n";
    opendir(DIR, $dir) || die "Could not open $dir - $!\n";
    for my $filefound (readdir(DIR)) {
        next if ($filefound =~ /^\./);
        my $fullpath = File::Spec->catfile($dir, $filefound);
        if (-d $fullpath) {
            processDirectory($fullpath);
        } else {
            my $stat = stat($fullpath);
            my $time = localtime($stat->mtime());
            print "$fullpath - ";
            printf("%04d-%02d\n", $time->year() + 1900, $time->mon() + 1);
        }
    }
}
    
